import { X, Plus, Check, ChevronLeft, ChevronRight, ArrowUp, ArrowDown, ArrowRight, Filter, Calendar, Search, Menu, User, LogOut, Download, Upload, Trash2, Target, TrendingUp, Wallet, Home, ArrowLeftRight, CreditCard, Banknote, ShoppingCart, Utensils, Car, HeartPulse, Film, BookOpen, Receipt, Gift, Briefcase, Building2, PlusCircle, MinusCircle } from 'lucide-react';

const s = { size: 16, strokeWidth: 1.5 };

export const Icn = {
  close: <X {...s} />,
  plus: <Plus {...s} />,
  check: <Check {...s} />,
  chevronLeft: <ChevronLeft {...s} />,
  chevronRight: <ChevronRight {...s} />,
  arrowUp: <ArrowUp {...s} />,
  arrowDown: <ArrowDown {...s} />,
  arrowRight: <ArrowRight {...s} />,
  filter: <Filter {...s} />,
  calendar: <Calendar {...s} />,
  search: <Search {...s} />,
  menu: <Menu {...s} />,
  user: <User {...s} />,
  logout: <LogOut {...s} />,
  download: <Download {...s} />,
  upload: <Upload {...s} />,
  trash: <Trash2 {...s} />,
  target: <Target {...s} />,
  trendingUp: <TrendingUp {...s} />,
  wallet: <Wallet {...s} />,
  home: <Home {...s} />,
  transfer: <ArrowLeftRight {...s} />,
  'credit-card': <CreditCard {...s} />,
  'building-bank': <Banknote {...s} />,
  'shopping-cart': <ShoppingCart {...s} />,
  food: <Utensils {...s} />,
  transport: <Car {...s} />,
  health: <HeartPulse {...s} />,
  entertainment: <Film {...s} />,
  education: <BookOpen {...s} />,
  bill: <Receipt {...s} />,
  gift: <Gift {...s} />,
  salary: <Briefcase {...s} />,
  investment: <TrendingUp {...s} />,
  business: <Building2 {...s} />,
  'other-income': <PlusCircle {...s} />,
  'other-expense': <MinusCircle {...s} />,
};
